### ISSUE TITLE
Attributes are nil

### ISSUE THREAD

**Issue by florianilch** [pauldix/sax-machine#30]
Somehow the attributes can't get displayed …

``` ruby
require 'sax-machine';

class AtomContent
  include SAXMachine
  attribute :type
  value :text
  element :test, :value => :type
end

node = AtomContent.parse('
    <content type="text">
        sample
    </content>
');
puts node;
puts node.type;
puts node.text;
```

**Comment by dewshick** [comment]
top node attributes are still nil, why issue was silently closed?

**Comment by krasnoukhov** [comment]
It's been 3+ years and original collaborators already moved off the project, so I'm not exactly sure. But I'd nice if you can write a failing spec and maybe go ahead and fix it. Thanks!
