### ISSUE TITLE
Cannot associate block with elements?

### ISSUE THREAD

**Issue by mgaudet** [pauldix/sax-machine#62]
Perhaps this is newbie problem, but it seems odd to me that a block cannot be
associated with an elements list...

```ruby
require 'sax-machine'

class ServiceResponse
  include SAXMachine
  elements :message, as: :messages do |message|
     puts "Got message: #{message}"
  end
end

response = ServiceResponse.parse("
  <response>
    <message>hi</message>
    <message>world</message>
  </response>
")

puts response.inspect
```

(The 'got message' puts never happens)

**Comment by krasnoukhov** [comment]
Hey @mgaudet, I was able to fix things you've reported. Can you please double check it with current master branch so I'll release a new version?

**Comment by mgaudet** [comment]
My tiny test looks good!

**Comment by krasnoukhov** [comment]
All right, thanks for collaborating :green_heart:

**Comment by mgaudet** [comment]
No problem.

On Mon, Jan 12, 2015 at 12:18 PM, Dmitry Krasnoukhov <
notifications@github.com> wrote:

> All right, thanks for collaborating [image: :green_heart:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pauldix/sax-machine/issues/62#issuecomment-69606980>.
>



-- 
- Matt
