### ISSUE TITLE
Elements with a hyphen in them fail to populate

### ISSUE THREAD

**Issue by claudijd** [pauldix/sax-machine#65]
I'm a relatively new sax-machine user, so please forgive my ignorance if I'm overlooking something obvious, but I think their might be an issue (or lack of support) for parsing class defined elements that contain a hyphen in their name.

*Example A (barbaz)*

    require 'sax-machine'

    class Bar
      include SAXMachine
      attribute :id
    end

    class Foo
      include SAXMachine
      attribute :id
      elements "barbaz", as: :bars, class: Bar
    end

    class Document
      include SAXMachine
      elements :foo, as: :foos, class: Foo
    end

    xml = "<?xml version='1.0' encoding='UTF-8'?>
    <foo id='1'>
      <barbaz id='1'>test</barbaz>
      <barbaz id='2'>test</barbaz>
    </foo>"

    doc = Document.parse(xml)
    doc.foos.first

When run in IRB results in:

    => #<Foo:0x007ff2a38cd988 @id="1", @bars=[#<Bar:0x007ff2a38cd190 @id="1">, #<Bar:0x007ff2a38cc6c8 @id="2">]>

*Example B (bar-baz)*

     require 'sax-machine'

    class Bar
      include SAXMachine
      attribute :id
    end

    class Foo
      include SAXMachine
      attribute :id
      elements "bar-baz", as: :bars, class: Bar
    end

    class Document
      include SAXMachine
      elements :foo, as: :foos, class: Foo
    end

    xml = "<?xml version='1.0' encoding='UTF-8'?>
    <foo id='1'>
      <bar-baz id='1'>test</bar-baz>
      <bar-baz id='2'>test</bar-baz>
    </foo>"

    doc = Document.parse(xml)
    doc.foos.first

When run in IRB results in:

    => #<Foo:0x007f9c0c084a30 @id="1">

What I would like to know is whether this is expected behavior or whether this is something that would be of interest in addressing in sax-machine.  Like I said above, I'm pretty new at it, so would be glad to find I'm just doing it wrong.

Thanks!

**Comment by trekdemo** [comment]
@claudijd here is the answer: https://github.com/pauldix/sax-machine/blob/master/spec/sax-machine/sax_document_spec.rb#L672-L682

you have to specify the element with underscores: `element :bar_baz` and it will work

**Comment by claudijd** [comment]
@trekdemo thanks!

**Comment by krasnoukhov** [comment]
@trekdemo Wow, thanks for the reply!

**Comment by epitron** [comment]
I just got bitten by this... I'm glad I found this ticket!

I must say that is a pretty counter-intuitive feature. I may even call it a bug, given that strings work for elements with colons in the names! (eg: `element :"dc:date", as: :published`)

I do like that you can pass an underscored symbol, and it'll look for a hyphenated tag, but it shouldn't *fail* to parse if you pass a hyphenated-string!

At the very least, the `README.md` should have an example that demonstrates this undocumented feature.

**Comment by krasnoukhov** [comment]
Makes sense. Do you mind opening a PR?

**Comment by epitron** [comment]
For the bug fix, or the readme?

**Comment by krasnoukhov** [comment]
Well, I don't think it's a good idea to change current behavior, since it would not be backwards-compatible and we'll have to release new major version, so the README addition would be appreciated as a only one option for now

**Comment by epitron** [comment]
I don't understand... the feature wouldn't break existing code, it would just make `element :"foo-bar", as: :foobar` work!

In fact, that code DOES work in old verison of sax-machine! (One of the reasons I was so confused when this happened to me.)

**Comment by krasnoukhov** [comment]
Ok, I probably misunderstood you. Please proceed with PR that fixes this issue, I'd be happy to merge if your solution is backwards compatible
