### ISSUE TITLE
Set class of attribute

### ISSUE THREAD

**Issue by sbuhr** [pauldix/sax-machine#67]
First of all: Awesome gem!

For a element I can do:

```
element :id, class: Integer
```

why can't I do

```
attribute :id, class: Integer
````

It doesn't throw an error, it just returns it as a String. Is there a way for attributes to accomplish that it returns the attribute in the desired class?

**Comment by krasnoukhov** [comment]
Hello! Thanks for the feedback. Currently there is no way to do that, but I think it would be a nice addition. Would you like to try implementing that?

**Comment by sbuhr** [comment]
I'm already doing it. Will send PR when all (and new) tests pass.



Von meinem iPhone gesendet

**Comment by krasnoukhov** [comment]
Nice! Thank you


On субота, 21 бер. 2015 р. at 21:16, sbuhr <notifications@github.com>, wrote:

I'm already doing it. Will send PR when all (and new) tests pass.




Von meinem iPhone gesendet

**Comment by sbuhr** [comment]
See #68
