### ISSUE TITLE
Is there a way to Proc/Lambda process element after declared?

### ISSUE THREAD

**Issue by tebayoso** [pauldix/sax-machine#72]
Assuming whe have an element:

```
<Dates PickUpDateTime="2015-04-22T11:00:00-05:00" ReturnDateTime="2015-04-23T11:00:00-05:00"></dates>
```

Is there a way to turn the attributes into DateTime instances?

Assuming we need to do DateTime.parse as a block to the element instead of DateTime.new

**Comment by krasnoukhov** [comment]
Please see Examples section in README: https://github.com/pauldix/sax-machine#examples
I believe that would work for you. Please let me know if it's not.

**Comment by tebayoso** [comment]
Didn't notice the title.strip when readed! You are a genius!
