### ISSUE TITLE
Issue with hypen in element name

### ISSUE THREAD

**Issue by fnoelscher** [pauldix/sax-machine#73]
sax-machine will not parse elements containing hyphens.
example:

```
class Test
  include SAXMachine

  element 'test:test-element', as: :test
end
```

using the following xml:

```
<test>
  <test:test-element>This won't work</test:test-element>
</test>
```

Am I doing something wrong?
Any help is greatly appreciated.

**Comment by krasnoukhov** [comment]
Hello, this is a duplicate of #65. Please see this [comment](https://github.com/pauldix/sax-machine/issues/65#issuecomment-70672042) for details.

**Comment by fnoelscher** [comment]
I didn't see that, thank you very much!
